
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ryurulzst
spec:
  serviceName: "ryurulzapp"
  replicas: 2
  selector:
    matchLabels:
      app: ryurulzapp
  template:
    metadata:
      labels:
        app: ryurulzapp
    spec:
      containers:
      - name: ryurulzapp
        image: riyaddocker/ryurulzapp
        ports:
        - containerPort: 5000
          name: ryurulzst
        volumeMounts:
        - name: www
          mountPath: /app
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
